-- ============================================================
-- EQUAL Clothing Store — Supabase Database Schema
-- Run this in: https://supabase.com/dashboard/project/mmnxnjqwrawcpkyebjzf/sql/new
-- ============================================================

-- 1. Products table
CREATE TABLE IF NOT EXISTS products (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  category    TEXT NOT NULL CHECK (category IN ('coats','shirts','pants','sweaters','dresses','accessories')),
  price       DECIMAL(10,2) NOT NULL,
  sizes       TEXT[] NOT NULL DEFAULT '{}',
  image_url   TEXT NOT NULL,
  description TEXT,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Orders table
CREATE TABLE IF NOT EXISTS orders (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT,
  customer_email TEXT,
  status        TEXT DEFAULT 'pending' CHECK (status IN ('pending','confirmed','shipped','delivered','cancelled')),
  total         DECIMAL(10,2) NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Order items (line items)
CREATE TABLE IF NOT EXISTS order_items (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id   BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id),
  quantity   INT NOT NULL DEFAULT 1,
  price      DECIMAL(10,2) NOT NULL
);

-- 4. Contact messages
CREATE TABLE IF NOT EXISTS contact_messages (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT,
  email      TEXT NOT NULL,
  message    TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- Seed data — 18 gender-neutral clothing items
-- ============================================================
INSERT INTO products (id, name, category, price, sizes, image_url, description) VALUES
(1,  'Oversized Wool Coat',    'coats',       189.00, '{"XS","S","M","L","XL","XXL"}',      'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=500&h=667&fit=crop', 'Heavy wool-blend coat with dropped shoulders and a relaxed silhouette.'),
(2,  'Classic Trench Coat',    'coats',       165.00, '{"XS","S","M","L","XL"}',             'https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?w=500&h=667&fit=crop', 'Water-resistant cotton twill trench with removable belt.'),
(3,  'Quilted Utility Jacket', 'coats',       135.00, '{"S","M","L","XL","XXL"}',             'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500&h=667&fit=crop', 'Lightweight quilted jacket with oversized pockets.'),
(4,  'Linen Button-Up',        'shirts',      72.00,  '{"XS","S","M","L","XL","XXL"}',       'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500&h=667&fit=crop', 'Breathable stonewashed linen with a relaxed collar.'),
(5,  'Organic Cotton Tee',     'shirts',      38.00,  '{"XXS","XS","S","M","L","XL","XXL"}',  'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=667&fit=crop', 'Heavyweight 220 GSM organic cotton. Pre-shrunk, boxy fit.'),
(6,  'Oversized Oxford Shirt', 'shirts',      84.00,  '{"S","M","L","XL","XXL"}',             'https://images.unsplash.com/photo-1598033129183-c4f50dac7c9c?w=500&h=667&fit=crop', 'Brushed cotton oxford with a generous cut.'),
(7,  'Wide-Leg Trousers',      'pants',       98.00,  '{"XS","S","M","L","XL","XXL"}',       'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500&h=667&fit=crop', 'High-waisted wide-leg trousers in TENCEL Lyocell.'),
(8,  'Cargo Pants',            'pants',       92.00,  '{"XS","S","M","L","XL"}',              'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=500&h=667&fit=crop', 'Relaxed-fit cotton twill cargos with flap pockets.'),
(9,  'Elasticated Chinos',     'pants',       78.00,  '{"XS","S","M","L","XL","XXL"}',       'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=500&h=667&fit=crop', 'Stretch cotton chinos with hidden elastic waistband.'),
(10, 'Chunky Knit Sweater',    'sweaters',    115.00, '{"S","M","L","XL","XXL"}',             'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=500&h=667&fit=crop', 'Heavy-gauge alpaca-blend knit with a funnel neck.'),
(11, 'Half-Zip Pullover',      'sweaters',    94.00,  '{"XS","S","M","L","XL","XXL"}',       'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=500&h=667&fit=crop', 'Brushed fleece mock-neck with quarter zip.'),
(12, 'Fine Merino Crewneck',   'sweaters',    128.00, '{"XS","S","M","L","XL"}',              'https://images.unsplash.com/photo-1434389677669-e08b4cda3a20?w=500&h=667&fit=crop', 'Extra-fine merino wool in a classic crewneck.'),
(13, 'Wrap Dress',             'dresses',     110.00, '{"XS","S","M","L","XL","XXL"}',       'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=500&h=667&fit=crop', 'Adjustable wrap dress in fluid TENCEL.'),
(14, 'Midi Skirt',             'dresses',     82.00,  '{"XS","S","M","L","XL","XXL"}',       'https://images.unsplash.com/photo-1583496661160-fb59e8146acf?w=500&h=667&fit=crop', 'A-line midi skirt in heavyweight crinkle viscose.'),
(15, 'Shirt Dress',            'dresses',     105.00, '{"XS","S","M","L","XL"}',              'https://images.unsplash.com/photo-1591369822096-ffd6890ab674?w=500&h=667&fit=crop', 'Poplin shirt dress with a relaxed fit.'),
(16, 'Canvas Tote Bag',        'accessories', 34.00,  '{"One Size"}',                          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=500&h=667&fit=crop', 'Heavy-duty organic cotton tote with reinforced handles.'),
(17, 'Ribbed Beanie',          'accessories', 26.00,  '{"One Size"}',                          'https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?w=500&h=667&fit=crop', 'Chunky rib-knit beanie in RWS-certified merino wool.'),
(18, 'Woven Scarf',            'accessories', 42.00,  '{"One Size"}',                          'https://images.unsplash.com/photo-1520903920243-00d22f015bba?w=500&h=667&fit=crop', 'Oversized woven scarf in a wool-modal blend.');

-- ============================================================
-- Row Level Security (RLS) — public read, authenticated write
-- ============================================================
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE contact_messages ENABLE ROW LEVEL SECURITY;

-- Products: anyone can read
CREATE POLICY "Public read products" ON products FOR SELECT USING (true);

-- Orders: anyone can create (guest checkout), only anon can read own
CREATE POLICY "Public create orders" ON orders FOR INSERT WITH CHECK (true);

-- Order items: public create
CREATE POLICY "Public create order_items" ON order_items FOR INSERT WITH CHECK (true);

-- Contact messages: public insert
CREATE POLICY "Public insert messages" ON contact_messages FOR INSERT WITH CHECK (true);
CREATE POLICY "Public read own messages" ON contact_messages FOR SELECT USING (true);
